services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wp-content:/var/www/html/wp-content
    environment:
      - .env
    depends_on:
      - db
    networks:
      - inception
    restart: unless-stopped

  db:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    environment:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/mariadb
      o: bind
  wp-content:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress

networks:
  inception: